name: Deploy to hodi.host via SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: "./"
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          port: "22"

